### ISSUE TITLE
Joining the organisation and introductory task

### ISSUE THREAD

**Issue by Mahimamohapatra** [websycode/support#9]
Hey it said to create an issue for joining the organisation. And I wanted to know ...it was mentioned that the task would be developed using HTML CSS JS and reactjs would be good if possible. So I want to know can I use AngularJS?

**Comment by Mahimamohapatra** [comment]
Yes mam, created the issue in websycode/support

**Comment by aakankshabhende** [comment]
Check your mail for the invitation link :) @Mahimamohapatra
